version: "3.9"

services:
  db:
    image: mariadb:10.6
    container_name: presenter-que-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: live_presenter
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: presenter-que
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_NAME: live_presenter
      DB_USER: your_db_user
      DB_PASS: your_db_password
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config:/var/www/html/config

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: presenter-que-pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:

