services:
  db:
    image: mariadb:10.6
    container_name: presenter-que-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: presenter-que
    ports:
      - "8080:80"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      PRODUCER_PASSWORD: ${PRODUCER_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config:/var/www/html/config

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: presenter-que-pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:


